### ISSUE TITLE
Socket.io provider

### ISSUE THREAD

**Issue by vizo** [catberry/catberry-recipes#8]
Because you are doing so great things, i would like to give something back ;)

If you are interested, i would like to share with you https://github.com/vizo/catberry-socket.io.
I can also transfer ownership if you want.

In the near future i will also make a CRUD socket.io provider, like sails.js have (client + server).

**Comment by pragmadash** [comment]
Thanks a lot!

Yeah, I think we can do that. 

Apparently we need a boilerplate for a catberry plugin :) Or maybe add a generator to CLI, who knows what's the best option.

The source code good looks completely good to me. Just a few suggestions:

* `package.json` seems to be copied from the package when it was installed like a dependency, therefore, it has so many redundant fields. NPM saves its service info in `package.json` when you install the package.
* the contributors list contains people who have not worked on your project
* `Readme.md` and `LICENSE` contain my name and email, in fact, you're the author and the project's name is different

Also, if you wanna keep helping the project I'd like to invite you to join the organization and keep working on the plugins as a part of it.

**Comment by vizo** [comment]
Sorrry, can you give me some hint or maybe PR for package.json (i copied it from catberry-jade) and just change it a bit, i am not (yet) so good in writing npm modules ;)

It would be my honor to join the organization. Are there any special obligations?

**Comment by pragmadash** [comment]
All these underscored fields should not be there https://github.com/vizo/catberry-socket.io/blob/develop/package.json#L2-L38

You copied this file from the package installed in your project, NPM changes `package.json` installing the package storing their its data about the installation process.

As you can see the original package.json of the jade plugin looks different https://github.com/catberry/catberry-jade/blob/develop/package.json

There are no obligations, but it would be nice to contribute occasionally and answer questions on the chat.

About transferring the repo, you are not able to transfer ownership to Catberry Organization directly, you have to transfer it to me (pragmadash) first and I can hand over the repo to the organization (because only an admin can do that).

**Comment by vizo** [comment]
Ok.. can you check package.json now :)?

**Comment by vizo** [comment]
Ok i sent you a transfer request.
